# .readthedocs.yaml
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools: {python: "3.10"}
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    pre_build:
      - pip install mkdocs==1.3.0
      - pip install mkdocs-material
      - pip install mkdocstrings
    post_install:
      - poetry install

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
